# Generated by Django 2.1 on 2018-10-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='p_des',
            new_name='p_path',
        ),
    ]
